{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-world
spec:
  port:
    targetPort: http 
  to:
    kind: Service
    name: hello-world
{{- end }}